### ISSUE TITLE
Serialization error with text sizes

### ISSUE THREAD

**Issue by ijprest** [ijprest/keyboard-layout-editor#104]
* Load VIC-20 layout
* Go to raw-data tab
* Change something
* Note that the text sizes of some keys have changed (e.g., '7')

**Comment by richfiles** [comment]
I've been noticing this in my own custom 75% layout. The key cap set I'm using has larger alphas than the text on all other keys. I keep getting sizing errors that cause either every alpha row after the QWERTY row to all be small text (like the non alpha keys), or everything not alpha to be large text (like the alpha keys). I have tried to manually edit the size of every individual key using the key property windows, and I have tried to edit it manually using the raw data window. Either way, I can make the keyboard look 100% correct, but it I click save, leave and reload the layout, the sizes have been changed again.
