### ISSUE TITLE
WASD added 8 more keycap colours...

### ISSUE THREAD

**Issue by jamadagni** [ijprest/keyboard-layout-editor#113]
Just got a mail from WASD keyboards notifying that they have now added 8 more colours to make the total 19. See for example: http://www.wasdkeyboards.com/index.php/products/keycap-set/88-key-iso-cherry-mx-keycap-set.html (the sampler kit page http://www.wasdkeyboards.com/index.php/products/sampler-kit/wasd-sampler-kit-o-ring-keycaps.html which you link as "more info" doesn't seem to be updated though).

**Comment by ijprest** [comment]
Thanks... I've added them.

**Comment by jasonm23** [comment]
![screen shot 2015-08-16 at 6 36 22 pm](https://cloud.githubusercontent.com/assets/71587/9292930/0f2395f8-4446-11e5-8c70-f2d26f5d0a82.png)

Looks like we're missing some

![screen shot 2015-08-16 at 6 37 56 pm](https://cloud.githubusercontent.com/assets/71587/9292933/280845be-4446-11e5-9e4f-cf5d1946dc96.png)

**Comment by jasonm23** [comment]
There's a deep red / crimson (next to red) and a darker blue, first on second row

**Comment by jasonm23** [comment]
Dark blue #002e5f

Dark red / crimson #5f3032

**Comment by jasonm23** [comment]
I'll add them to colors.json now.

**Comment by jasonm23** [comment]
#120
