### ISSUE TITLE
Add support for key class/style

### ISSUE THREAD

**Issue by skullydazed** [ijprest/keyboard-layout-editor#117]
Currently each key is self contained and if you want to make changes to multiple keys you have to hold down ctrl or alt while you select only the keys you want to change. For some designs, particularly pixel art designs, this makes palette shifting a tedious affair.

Adding CSS-like style support could allow people to define classes for their keys, and then changing your colors/fonts/etc is simply a matter of changing the style definition rather than having to select groups of keys (which can be error prone.)

**Comment by iandoug** [comment]
Unless I'm mistaken that's already there ... 
https://github.com/ijprest/keyboard-layout-editor/wiki/Custom-Styles

**Comment by skullydazed** [comment]
That could be used as the backend support, yes. I'm looking for a interface for this in the UI so I don't have to go messing about in CSS.

**Comment by iandoug** [comment]
This might overlap #6 to some extent.

**Comment by iandoug** [comment]
Are you thinking of something like "groups" where you can 'invent' a group name along with characteristics, and then assign various keys as belonging to that group (eg TenKeys or WASD), without having to manually code the CSS yourself?

**Comment by ijprest** [comment]
Yeah, I think think is a duplicate of #6.  I called them 'prototypes', but it's basically defining a style for a key... so you can edit the prototype and the properties of all the keys to which the prototype is 'applied' would update.

#99 ("selection groups") is another idea that would solve your particular workflow (by allowing you to quickly recall the same group of selected keys).

**Comment by skullydazed** [comment]
Ah, yeah, looks like #6 covers this if that includes the UI component. When I was scanning the list of issues that didn't jump out at me as something related. I think "Style", "Format", "Type", or something else might better convey the intent.

I think #99 could also work for my use case, but that also makes getting at this information from external tools more difficult.
