### ISSUE TITLE
Add method for bulk-changing legend position

### ISSUE THREAD

**Issue by skullydazed** [ijprest/keyboard-layout-editor#127]
I love the new legend layout in the raw data ({a:N}) but I wish I had an easier way to apply it to lots of keys at once. For example, when I start a new keyset design I load the 104 key preset, then have to spend a few minutes moving labels around, etc, before I get to start on my actual design work. Selecting a group of keys and moving where the labels are would save a lot of time.

**Comment by iandoug** [comment]
When Jordi and I were discussing the presets we considered having 'blank' layouts as well eg 104 with no legends. Would that work for you? Or just extra work putting all the labels on again? I suppose a little function on the keyboard properties page to "move all legends to top left on key" or somesuch would suit your needs better?

**Comment by skullydazed** [comment]
Yeah, a blank preset would just mean work to repopulate them. It's easy to get a blank preset now by hitting ctrl-a then clearing out the text inputs.

There's a few details in the implementation you suggest that I worry about. Would I be able to move in any direction? The preset has them at the top left already, and what I need to do for most of my sets is center the single-legend keys (alphas) along both axes and center the keys with 2 legends vertically. However, I see other designers move them to the bottom left or right.

By and large, though, that feels like the right direction.

**Comment by ijprest** [comment]
There is now a 'tools' tab that has functions to do bulk alignment and/or moving of labels.  The 'align' function will probably solve your specific problem, while the 'move' function offers more granular control.  There's also functions to remove text labels, should you need that.  

Thanks to @iandoug for the initial implementation!

**Comment by skullydazed** [comment]
Thanks guys! I just tried it out and it works great!
