### ISSUE TITLE
Improve spacing for nav and num pad keys in 104/105 layout presets

### ISSUE THREAD

**Issue by tylert** [ijprest/keyboard-layout-editor#131]
The "ANSI 104", "ANSI 104 (big-ass enter)" and "ISO 105" preset layouts, currently have a 0.5 unit spacing between the "main keys" and the "navigation keys" and a 0.5 unit spacing between the "navigation keys" and the num pad.

On most commercial keyboards, this spacing appears to normally be 0.25 units.

**Comment by ijprest** [comment]
Weird... how the hell did I not notice this.

**Comment by tylert** [comment]
Heh... Totally understandable oversight.  Thanks for the merge and thanks for the great tool.
