### ISSUE TITLE
Planck

### ISSUE THREAD

**Issue by iandoug** [ijprest/keyboard-layout-editor#135]
Add a Planck preset ... I've seen various comments in various fora requesting one. I have a few json files gathered off the web if you like.

**Comment by ijprest** [comment]
The layout is simple enough.  I suspect we'd want a "preset", devoid of formatting and stuff, so that users could enter their own layers and such... sort-of like the current ErgoDox layout.  Is this what you had in mind?

**Comment by iandoug** [comment]
On Sunday 20 September 2015 20:26:36 Ian Prest wrote:

> The layout is simple enough.  I suspect we'd want a "preset", devoid of
> formatting and stuff, so that users could enter their own layers and
> such... sort-of like the current ErgoDox layout.  Is this what you had in
> mind?

I'll send you my collection ... it's not really my idea, just something I 
picked up more than once while reading various keyboard fora....

cheers, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273
