### ISSUE TITLE
Font generation in Make file

### ISSUE THREAD

**Issue by iandoug** [ijprest/keyboard-layout-editor#137]
Fonts not generate during make.

**Comment by iandoug** [comment]
The code to generate the fonts does not work on my system. I can generate the fonts if I run fontforge manually, and tweak the .pe file to generate the font files by name. Make install and make run through without warnings or errors. I only noticed now because previously I had the fonts that would be generated.

**Comment by ijprest** [comment]
Note that the makefiles don't generate the fonts by default because checking the dependencies takes a few seconds---even if there's nothing to do!---and I didn't want to slow down the "normal" case of regenerating CSS, etc., which is done much more frequently.

You can build them with "make fonts" (or "make fonts -B" to force it).  Does this command give you an error?

**Comment by iandoug** [comment]
On Sunday 20 September 2015 20:24:31 Ian Prest wrote:

> You can build them with "make fonts" (or "make fonts -B" to force it).  Does
> this command give you an error?

ah. that seems to work, thanks :-)

~/projects/keyboard-layout-editor (master) $ make fonts
fontforge -quiet -script "font-src/kbd-webfont.pe" "font-src/kbd-webfont.sfd" 
"fonts/kbd-webfont.ttf"
fontforge -quiet -script "font-src/kbd-webfont.pe" "font-src/kbd-webfont.sfd" 
"fonts/kbd-webfont.eot"
fontforge -quiet -script "font-src/kbd-webfont.pe" "font-src/kbd-webfont.sfd" 
"fonts/kbd-webfont.svg"
fontforge -quiet -script "font-src/kbd-webfont.pe" "font-src/kbd-webfont.sfd" 
"fonts/kbd-webfont.woff"
fontforge -quiet -script "font-src/combining-diacritical.pe" "font-
src/combining-diacritical.sfd" "fonts/combining-diacritical.ttf"
fontforge -quiet -script "font-src/combining-diacritical.pe" "font-
src/combining-diacritical.sfd" "fonts/combining-diacritical.eot"
fontforge -quiet -script "font-src/combining-diacritical.pe" "font-
src/combining-diacritical.sfd" "fonts/combining-diacritical.svg"
fontforge -quiet -script "font-src/combining-diacritical.pe" "font-
src/combining-diacritical.sfd" "fonts/combining-diacritical.woff"

Cheers, Ian
-- 
ian@zti.co.za http://www.zti.co.za
Zero 2 Infinity - The net.works
Phone +27-21-975-7273

**Comment by ijprest** [comment]
Cool.  I'll close this.  (I also added a note about this to the README, though the instructions there are pretty sparse.)
