### ISSUE TITLE
Missing colors

### ISSUE THREAD

**Issue by sitrec** [ijprest/keyboard-layout-editor#141]
There are a bunch of colors missing in the SP PBT list, I noticed most of the brown ones aren't there.
http://www.keycapsdirect.com/pbtcolors.php

**Comment by ijprest** [comment]
FWIW, I sampled everything for which I had a physical color chip.  My chips are from ~2013, but SP has been known to modify their color selection over time.

Looking closely at the thumbnail, you can see that the thumbnail is actually for ABS colors.  Compare the thumbnail with the large ABS image from here:  http://www.keycapsdirect.com/images/colors/absblackbrown.JPG

When you click through to the full-sized image, there are only four colors in the PBT black/brown group.  Two already existed, and I can't make out a color name for the black one.  But it looks like TGT was missing, so I added it (with a disclaimer that the color hasn't been color-corrected).

Let me know if you notice any other missing colors.

**Comment by iandoug** [comment]
the black one says BLACK :-) ... although there does seem to some faint text at the top as well (possibly IEC).
BTW the TGT should be TGJ.

**Comment by ijprest** [comment]
Right you are!  You must have better eyes than me (or just have your monitor brightness set really high)... I couldn't make that out without processing the image.

I've added it, and fixed the TGT/TGJ mistake.

I think the text at the top you refer to is PBT (it's upside down... raised lettering on the plastic chip itself).

**Comment by iandoug** [comment]
Yes, when I flipped the pic and enlarged the PBT became clear. The black was reasonably clear to me, my monitor is set at default setting AFAIK. Currently using Philips 21:9 298P4QJEB/00. Maybe I had a different version of the image, saved a few months ago.

**Comment by Pitometsu** [comment]
Maybe you will use `#6c5445` for TGJ? Because it's too dark.
