### ISSUE TITLE
Custom CSS breaks character picker

### ISSUE THREAD

**Issue by iandoug** [ijprest/keyboard-layout-editor#164]
Discovered something... if I set up a custom font as per the help [Loading & Using Fonts], and then try and use the Keyboard-Layout-Editor icons, these icons are broken... a mismash of what should be there, plus other stuff.

I assume it is because of this line
- {font-family: blahblah;}

which is replacing too much. Possibly going to have to use a more conservative approach like in your PET board.

Trying to make time to fix the other broken things (and get my own keyboard done...)

**Comment by ijprest** [comment]
You duplicated your own bug #143.  :)
