### ISSUE TITLE
GMK colors are out of date.

### ISSUE THREAD

**Issue by got1337skillz** [ijprest/keyboard-layout-editor#169]
The gmk color options are out of date.
Here is an image I got from GMK today.
http://imgur.com/ILNnXOm

Is there a way to get this updated?
![color samples_gmk](https://cloud.githubusercontent.com/assets/2797710/16323109/7f6960f8-3965-11e6-9aa2-a4d0d6a77703.JPG)

**Comment by iandoug** [comment]
AFAIK IJP has a fancy tool that analyzes the light coming off the key, and turns it into a colour code. So he will need a set of keys (or plastic samples)... taking colours off web photos is not accurate.
I'll see if they can send me the RGB values in the mean time, but I think last time I asked they didn't have them.

**Comment by NiceAndCreamy** [comment]
Any chance you could update the GMK pallet if I provide the RGB values? I tried to do it using the chrome HTML editor but once I change everything it doesn't allow me to add the colors to the keyboard.

**Comment by iandoug** [comment]
Sorry, I have now mailed my contact at GMK to ask if they have the actual RGB values, taking them off a jpg will "work" but won't be completely accurate.

You could always download the repo and run it locally, and then edit the file with the colours in. (colors.json). Note that AFAIK Ian Prest put the colour on the side of the key not the top.

Just noticed the note in the file re GMK"s keys : "These are samples from a picture posted on GeekHack. No attempt at color-correction has been made." ...  so I suppose your suggestion may work.  Let's just wait a day or so to see if GMK comes back to me.

I also need to hear from them if the previous range is discontinued.

Will revert.

Cheers, Ian

**Comment by NiceAndCreamy** [comment]
I believe the previous colors are discontinued because they have changed plastic manufactures. I changed the colors.json to samples pulled from the tops of the caps in the pictures above but I   couldn't be arsed to get a local site running. 

`{ "name": "UN0001", "r":243, "g":255, "b":255 },
			{ "name": "CP", "r":235, "g":242, "b":250 },
			{ "name": "3K", "r":224, "g":233, "b":240 },
			{ "name": "2M", "r":215, "g":234, "b":248 },
			{ "name": "L9", "r":231, "g":241, "b":243 },
			{ "name": "U9", "r":197, "g":209, "b":209 },
			{ "name": "2B", "r":147, "g":165, "b":185 },
			{ "name": "CC", "r":114, "g":123, "b":130 },
			{ "name": "N9", "r":80, "g":93, "b":109 },
			{ "name": "CR", "r":39, "g":43, "b":54 },
			{ "name": "3B", "r":155, "g":197, "b":185 },
			{ "name": "AE", "r":91, "g":204, "b":88 },
			{ "name": "N7", "r":36, "g":167, "b":125 },
			{ "name": "UN6037", "r":25, "g":212, "b":247 },
			{ "name": "N5", "r":22, "g":263, "b":255 },
			{ "name": "V4", "r":13, "g":88, "b":216 },
			{ "name": "UN6046", "r":161, "g":128, "b":199 },
			{ "name": "3C", "r":241, "g":181, "b":181 },
			{ "name": "UN33656", "r":255, "g":104, "b":171 },
			{ "name": "V1", "r":201, "g":194, "b":176 },
			{ "name": "V2", "r":255, "g":146, "b":51 },
			{ "name": "N6", "r":247, "g":204, "b":37 },
			{ "name": "CV", "r":252, "g":229, "b":61 }`

**Comment by iandoug** [comment]
GMK have come back to me, they're getting an engineer to get the proper RGB colour codes to send to me. Hopefully in the next few days.

**Comment by NiceAndCreamy** [comment]
Awesome, thanks so much.

**Comment by NiceAndCreamy** [comment]
Any update?

**Comment by iandoug** [comment]
Regret not yet, I'll send a followup next week.

**Comment by iandoug** [comment]
I followed up yesterday (apologies), my contact at GMK was on leave anyway and is back today.
In the mean time I checked my mailbox today and wow, they had sent me a colour ring. I will see what results I get from "scanning' them.... else I'll have to make a plan like IJP did and get one of those fancy "get a colour" gadgets that uses a special light and electronics to determine an object's colour. Hopefully GMK will do that part for us and send me the RGB codes instead. :-)

**Comment by iandoug** [comment]
Scanning did not produce good results, I tried "colour analyser" apps on my phone but results were also not good. So resorted to taking pictures with a decent camera, that produces reasonable results. Done about half the keycaps, hope to have the rest done shortly. I'll send IJP a patch but he's been quiet lately so don't know when he will get it onto the live site. GMK sent me a link to their official pic of the keycaps, but the angle and lighting produce numerous colours on each surface, so I can't sample off that.

**Comment by iandoug** [comment]
BTW the stuff I'm working with is 35 colours, if I remember correctly... more than in your pic. Some are same as previous range.

**Comment by potatobot8** [comment]
i cant wait for the new colors, im trying to make a mockup and updated colors would be great news :D

**Comment by iandoug** [comment]
These are the ones I have done so far. Still 9 to do. In a worst-case scenario you can manually set the colour on a key and they copy it to the others. Will try and finish this Tuesday.
	{
		"name" : "GMK 2016 (Alpha)",
		"href" : "https://uniqey.zendesk.com/hc/en-us/article_attachments/205091409/keycap_colors_2016.jpg",
		"description" : "The new codes are taken from photographs of the actual keys (not the one above). No attempt at color-correction has been made. Colors are reasonable for use, if not exactly accurate. Color codes for keys in previous collection were left unchanged for consistency.",
		"colors" : [
			{ "name": "2B", "r":133, "g":138, "b":141 },
			{ "name": "2M", "r":215, "g":225, "b":235 },
			{ "name": "3A", "r":135, "g":188, "b":158 },
			{ "name": "3B", "r":129, "g":162, "b":145 },
			{ "name": "3C", "r":216, "g":151, "b":147 },
			{ "name": "3K", "r":217, "g":220, "b":225 },
			{ "name": "AE", "r":101, "g":175, "b":76 },
			{ "name": "BJ", "r":154, "g":151, "b":144 },
			{ "name": "CB", "r":167, "g":163, "b":152 },
			{ "name": "CC", "r":108, "g":115, "b":107 },
			{ "name": "CR", "r":29, "g":51, "b":39 },
			{ "name": "CV", "r":253, "g":231, "b":49 },
			{ "name": "GE1", "r":196, "g":188, "b":43 },
			{ "name": "L9", "r":227, "g":229, "b":216 },
			{ "name": "MG1", "r":164, "g":45, "b":75 },
			{ "name": "N5", "r":0, "g":141, "b":234 },
			{ "name": "N6", "r":211, "g":161, "b":46 },
			{ "name": "N7", "r":5, "g":133, "b":80 },
			{ "name": "P3", "r":177, "g":73, "b":62 },
			{ "name": "RO1", "r":94, "g":24, "b":24 },
			{ "name": "RO2", "r":224, "g":80, "b":71 },
			{ "name": "U9", "r":185, "g":186, "b":180 },
			{ "name": "V1", "r":238, "g":73, "b":66 },
			{ "name": "V2", "r":219, "g":112, "b":60 },
			{ "name": "V4", "r":2, "g":85, "b":187 }
		]
	},
ToDo: BR1, TU1, TU2, T9,R01,DY, CP, GR1, WS1

**Comment by potatobot8** [comment]
Im really new here, how do i use those codes? :))

**Comment by iandoug** [comment]
For some reason the clever people who did HTML and CSS decided to have two different standards for specifying numbers... the numbers above are so-called RGB values, one each for Red, Green and Blue, on a scale of 0 - 255. 
There is an equivalent hex version for that, in the format #RRGGBB where each pair can range from 00 to FF hex (same as 0 to 255 decimal).
So you will need to convert those numbers above to the hex version (until such time as we can get them loaded on the live site ... see below).
Go here: http://hex.colorrrs.com/  
and where it says RGB, type in a set of numbers from above, eg the last one would be 2,85,187
The site will show you the equivalent as #0255BB
Now take that #0255BB and go to KLE, select a key, and on the Properties tab, paste that number into the Key Color field. You will have to rinse and repeat for each key, I'm afraid.

Regarding the new colours, I added in the ones I photographed, but when I was checking them I noticed two things:
1. grays and whites render on screen a bit differently to the keycap. Not sure why, I used the same process for them as for the brighter colours. Have reshot them to see if I can get better results.

2. the existing colour codes that IJP picked from an old photo do not look like the actual key colours ... so I have taken photos in sunlight with no flash, of all the keycaps, and need to load and check them. Need to do this in daylight else the glare from the screen gets in the way of accurate colour comparisons.

In the mean time I am happy with these:
			{ "name": "BR1", "r":119, "g":74, "b":45 },
			{ "name": "CR", "r":29, "g":51, "b":39 },
			{ "name": "DY", "r":130, "g":105, "b":171 },
			{ "name": "N6", "r":211, "g":161, "b":46 },
			{ "name": "N7", "r":5, "g":133, "b":80 },
			{ "name": "RO1", "r":173, "g":69, "b":70 },
			{ "name": "RO2", "r":224, "g":80, "b":71 },
			{ "name": "V1", "r":238, "g":73, "b":66 },
			{ "name": "WS1", "r":238, "g":239, "b":234 }

Will try and load and test the rest tomorrow.

Cheers, Ian

**Comment by NiceAndCreamy** [comment]
Thanks so much for this, they don't have to be 100% perfect as GMK offers renders once you get your set finalized. This tool is just a good way to visualize your set and make quick changes too it while being in the ballpark for color.

**Comment by iandoug** [comment]
Mmm... do you perhaps have a URL with such a render?

thanks, Ian

**Comment by NiceAndCreamy** [comment]
Here is a recent one I found https://www.keyclack.com/wp-content/uploads/2016/08/M8Oyad8.jpg

**Comment by iandoug** [comment]
Thanks, that looks like a photo not a render (ie computer-generated). I was hoping to be able to get them to create such a render and then borrow the colour codes.

The 'photo' approach is not working too well .. colours do not come out accurate due to the plastic being shiny and reflecting the sunlight. So am busy with Plan B, which is to manually match the colour on screen to how it actually looks. Downside is that it's a slow and frustrating process, but at least the results are reasonable.

**Comment by NiceAndCreamy** [comment]
Oh its a render alright, that set hasn't been produced yet. Thanks for all
of the work on this though, really appreciate it.

**Comment by iandoug** [comment]
I've mailed Jessica to ask if she has the colour codes, since she seems to make lots of mockups ... must have really fancy software.

**Comment by iandoug** [comment]
Which colours are most urgent?

**Comment by NiceAndCreamy** [comment]
Personally, Im looking for their blacks, grays, and yellow, orange, red

**Comment by iandoug** [comment]
Still busy but here's the colours you requested. They're at least reasonable if not perfect, and better than the existing codes (at least on my monitor and to my eyes :-) )
Use the #numbers at the end of each line to set the colour in KLE.

brown		{ "name": "BR1", "r":122, "g":91, "b":58 },  #7a5b3a
black		{ "name": "CR", "r":34, "g":34, "b":34 },   #222222
dark grey/blackish		{ "name": "N9", "r":62, "g":64, "b":42 },   #3E402A
grey		{ "name": "BJ", "r":176, "g":175, "b":107 }, #b0af6b
grey		{ "name": "CB", "r":195, "g":196, "b":112 }, #C3C470
beige/grey		{ "name": "U9", "r":207, "g":203, "b":118 }, #CFCB76
grey		{ "name": "2B", "r":147, "g":150, "b":92 }, #93965c
grey		{ "name": "CC", "r":135, "g":126, "b":74 }, #877e4a
yellow		{ "name": "GE1", "r":255, "g":245, "b":56 }, #FFF538
yellow		{ "name": "CV", "r":250, "g":217, "b":3 }, #FAD903
yellow		{ "name": "N6", "r":247, "g":186, "b":32 }, #f7ba20
red	 	    { "name": "RO1", "r":158, "g":52, "b":52 }, #9e3434
red			{ "name": "RO2", "r":235, "g":43, "b":30 }, #eb2b1e
orange/red		{ "name": "V1", "r":247, "g":74, "b":47 }, #f74a2f
orange		{ "name": "V2", "r":242, "g":124, "b":34 }, #f27c22
red			{ "name": "P3", "r":217, "g":59, "b":49 },  #d93b31
cerise/pink (bright)	{ "name": "MG1", "r":232, "g":94, "b":100 }, #e85e64
purple		{ "name": "DY", "r":111, "g":89, "b":122 }, #6f597a
white		{ "name": "WS1", "r":250, "g":247, "b":170 } #faf7aa
green		{ "name": "N7", "r":0, "g":145, "b":76 },#00914c
pink (dusty)	{ "name": "3C", "r":232, "g":160, "b":109 },#e8a06d
blue		{ "name": "V4", "r":0, "g":110, "b":122 },#006e7a

More later... about 13 to go. Whites, blues/greens

**Comment by NiceAndCreamy** [comment]
Thanks so much! I wonder if there is anyway to update the pallet locally so
I don't have to do each key individually.

**Comment by iandoug** [comment]
Once you set the colour for a key, it is available in your  "current key colors" in the Color Swatches.
What you could do is add a few new keys off to the side, make one each the colours that you want, and then just work with your own custom palette... then delete the dummies when you're done :-)

**Comment by iandoug** [comment]
Here's the blue/greens and grey/offwhite/whites
Will send a pull request through to IJP to get them loaded on the live site.
bluegreen			{ "name": "TU1", "r":05, "g":117, "b":119 }, #00756d
bluegreen			{ "name": "TU2", "r":90, "g":201, "b":172 }, #5ac9ac
green			{ "name": "3A", "r":148, "g":222, "b":138 }, #94de8a
green			{ "name": "3B", "r":132, "g":196, "b":126 }, #84c47e
blue			{ "name": "N5", "r":0, "g":166, "b":1894 },  #00a6bd
green			{ "name": "AE", "r":116, "g":201, "b":87 },  #74C957
whitish			{ "name": "L9", "r":230, "g":245, "b":176 }, #e6f5b0
whitish			{ "name": "T9", "r":233, "g":245, "b":206 },  #e9f5ce
whitish			{ "name": "2M", "r":245, "g":255, "b":204 }, #F5FFCC
whitish			{ "name": "3K", "r":247, "g":252, "b":212 }, #f7fcd4
whitish			{ "name": "CP", "r":241, "g":252, "b":210 }, #f1fcd2
whitish			{ "name": "GR1", "r":218, "g":250, "b":215 }, #dafad7

**Comment by iandoug** [comment]
Damn. Thought  I was done but looking at them in the palette some of them look wrong again. It's difficult to match pigment colours (reflected light) against screen colours (direct light). Whitish colours particularly tricky :-)
Will try again.

**Comment by pmck91** [comment]
Any update?

**Comment by iandoug** [comment]
Hi.. yeah... We had another go at the blues, greys and whites, but were not successful. Monitors not capable of displaying some colours, it seems.
So I have today air-mailed the sample ring off to Ian Prest, he has the machines necessary to do objective colour sampling.

**Comment by christopherjanzen** [comment]
Where did this end up? Is KLE updated with the latest samples now?

**Comment by iandoug** [comment]
I sent them snailmail to IJP, and if I remember correctly, he scanned them with is fancy colour scanner identifier and updated them on KLE. It was almost three years ago ...

**Comment by ijprest** [comment]
Yes!  Was completed in 69ef807bb8647f629e095d5ee39da79523850594.  I neglected to close this out at the time.

Raw photospectrometer data is here:  https://docs.google.com/spreadsheets/d/1y3rkeCwR081D3reGhYMwmTfEn2CzF9ueALf8jwLuhEI
Conversion to sRGB data is here:
https://docs.google.com/spreadsheets/d/1JDdOLHIYYCjY31gdc7Yakign6xkPFAi24xeAYfi6E-A
