### ISSUE TITLE
Only support 30 layouts?

### ISSUE THREAD

**Issue by sitrec** [ijprest/keyboard-layout-editor#176]
Hi,
It seems like the site will automatically remove layouts if there are more than 30.
I was not aware of this so now a very important layout that I keep updated with keyboard shortcuts I'm using is gone. I still have the Gist  apparently but I don't know how to convert it to work with KLE.

It would be great if it supported having more layouts or at least warned you before removing old ones.

Cheers

**Comment by alexives** [comment]
The easiest way to convert gist -> kle is to go to `http://www.keyboard-layout-editor.com/#/gists/gist_id_goes_here` and replace `gist_id_goes_here` with the last part of the url when you click on an individual gist. 

I don't know anything about the 30 layout limit, but hopefully this helps.

**Comment by ju0** [comment]
I think I see why we only are able to view the latest 30 layouts we save. It has to do with how the gists are being pulled from github, I think. https://developer.github.com/v3/#pagination

**Comment by ijprest** [comment]
Duplicate of #156.
