### ISSUE TITLE
GitHub sign-in doesn't work on Firefox

### ISSUE THREAD

**Issue by jakllsch** [ijprest/keyboard-layout-editor#179]
When attempting to sign-in to KLE I get a "An error occurred during login: Could not communicate with the gatekeeper process." message in a red box at the bottom of the page, and I can't access my KLE gists.  Browser is Firefox 45.

**Comment by ijprest** [comment]
Is this still happening?  I've just tried current versions of Edge, Chrome, and Firefox (50.0a), and am not having troubles in any of them.

The gatekeeper is hosted separately (on Azure)... it's possible there was some transient error  that prevented it from working.

**Comment by jakllsch** [comment]
I don't run non-ESR Firefox...  but I might be able to test it in a sandbox sometime before Firefox 52.

**Comment by iandoug** [comment]
I'm on 45.4.0 on Linux, and it works fine. Possibly something to do with the fact that the login spawns a window? Are you perhaps blocking new windows opening?

**Comment by jakllsch** [comment]
It must be something with my configuration and/or add-ons.  Nightly 45.2.0 on NetBSD with a fresh/default profile works for sign-in.

**Comment by jakllsch** [comment]
Follow up:  I had to tell NoScript to allow scripts from kle-gatekeeper.azurewebsites.net.
