### ISSUE TITLE
Add a "character picker" to make selection of symbol characters easier.

### ISSUE THREAD

**Issue by ijprest** [ijprest/keyboard-layout-editor#18]
Even though the fonts contain the appropriate glyphs, it's sometimes difficult to find many symbol characters in the Unicode ranges, e.g,. the arrow symbols, etc.

It would be nice to have a character picker to make finding and using these glyphs easier.

**Comment by ijprest** [comment]
* Also want FontAwesome glyphs (all of them? or just reasonable ones, like Windows logo, etc.?)

**Comment by D1SC0tech** [comment]
Maybe just the reasonable ones for now? (OSes, keyboard, etc)

**Comment by ijprest** [comment]
Implemented in c302548b247d059a74eee9c160578ab21bec9e4b.
