### ISSUE TITLE
Login with GitHub does not work

### ISSUE THREAD

**Issue by kronn** [ijprest/keyboard-layout-editor#183]
After clicking the "Sign in with GitHub"-Link (and probably a few redirects), I am not logged in and the following message is visible:

> An error occurred during login: Could not communicate with the gatekeeper process.

I suspect something minor changed in the interaction and wanted to let you know.

**Comment by brianjking** [comment]
@kronn Works for me right now.

**Comment by ijprest** [comment]
@kronn:  It's working for me, too, on multiple systems and different browsers.  It was probably a temporary error.  Please try it again, and re-open if you continue to have problems.

**Comment by kronn** [comment]
Ah, okay. I'll try tomorrow again. 

Let's just hope that this was on my end. I would like that kind of error ;-) "the pebcak"

**Comment by kronn** [comment]
I was some combination of uBlock origin and uMatrix, both browser-plugins for limiting requests. I suspect that uMatrix was missing some rule to allow third-party content.
