### ISSUE TITLE
Add the ability to reference an external image/icon as a keycap logo.

### ISSUE THREAD

**Issue by ijprest** [ijprest/keyboard-layout-editor#19]
Some layouts may want to use custom icons on key caps. e.g., the DSA-retro set used the Commodore logo on the Windows-key, and may sets include a "GEEK HACK" custom key.

Since we can't possibly anticipate everything that everybody may want, add the ability to reference an externally hosted image/icon/SVG file.

**Comment by jasonm23** [comment]
Custom CSS closes this I think

**Comment by ijprest** [comment]
Yeah... I'll close this.  Though I think the process could be made easier, so I logged #102 to add some buttons or something to automate generating CSS for custom glyphs/images.

**Comment by iandoug** [comment]
Um, I just reference external images with the img tag ... works fine. For example the running man on PKB escape key, or the Vionia logo. Though I suppose having a way to add it without requiring users to know HTML or CSS would be cool.
