### ISSUE TITLE
Increase maximum size of key (currently 18x18)

### ISSUE THREAD

**Issue by au-chadl** [ijprest/keyboard-layout-editor#200]
With the layout editor I need the width 20 (would prefer at least 21 or 22), the current maximum is 18. The height is 6.5
Also on the plate & case builder, the switch layer does not look right, with this code

It is for this keyboard (Commodore 128D):
[{f:2},"ESC",{x:-1,a:7,f:3,w:18,h:6.5,d:true},"",{x:-17,a:4,f:2},"TAB","ALT",{a:5},"CAPS  LOCK",{x:2,a:4},"HELP","LINE FEED",{f:1},"40/80 DISPLAY",{f:2},"NO  SCROLL",{x:2,a:7},"↑",{f:3},"↓","←","→",{x:1,a:4,f:2}," F1\nF2","F3\nF4","F5\nF6","F7\nF8"],
[{y:0.5,f:7},"←",{f:3},"!\n1","\"\n2","#\n3","$\n4","%\n5","&\n6","'\n7","(\n8",")\n9","\n0","+","-","£","CLR HOME","INST DEL",{x:1},"7","8","9","+"],
[{w:1.5},"CONTROL","Q","W","E","R","T","Y","U","I","O","P","@","*","↑",{w:1.5},"RESTORE",{x:1},"4","5","6","-"],
["RUN STOP","SHIFT LOCK","A","S","D","F","G","H","J","K","L","[\n:","]\n;","=",{w:2},"RETURN",{x:1},"1","2","3",{h:2},"ENTER"],
["C=",{w:1.5},"SHIFT","Z","X","C","V","B","N","M","<\n,",">\n.","?\n/",{w:1.5},"SHIFT",{a:5},"↑\n↓\n\n\n\n\nCRSR","←\n→\n\n\n\n\nCRSR",{x:1,a:4,w:2},"0","."],
[{x:4.75,a:7,w:6.5},""]

**Comment by ijprest** [comment]
I've updated the max size to 24x24.
