### ISSUE TITLE
[Feature Request] Add ANSI MINILA to the presets.

### ISSUE THREAD

**Issue by carlsmith** [ijprest/keyboard-layout-editor#203]
Now that keycap sets are available for the ANSI version of the Filco Majestouch MINILA, it would be handy to have that model of keyboard in the presets.

I've attached a JSON file with everything you need, but renamed to look like a txt file, as GitHub does not allow uploading JSON files with comments.

[ansi_minila.txt](https://github.com/ijprest/keyboard-layout-editor/files/966225/ansi_minila.txt)

**Comment by brianjking** [comment]
@carlsmith Create a pull request and submit the layout as the `.json` layout format.

**Comment by carlsmith** [comment]
Thanks @brianjking - will do.
