### ISSUE TITLE
Keyboard shortcuts website

### ISSUE THREAD

**Issue by albfan** [ijprest/keyboard-layout-editor#213]
Is it possible to add some behaviour for keyboards? like:

1. press Ctrl, highlight all keys linked to it, and a list of actions. Press a second key and highlight only that unique command. i. e.

Press Ctrl, highlight:

- X
- C
- V

And show list of actions:

- Cut Action
- Copy Action
- paste Action

Press V:

Show only:

-  Paste action

2. Add program shorcuts list (tmux, vim, emacs, ...)

3. Allow to filter on those actions to see the key combination (look for paste) and get Shift+Insert or Ctrl+V or p (for vim)

4. See all the combinations a program uses to see avaliable shortcuts and look for consistency (like hiding non used keys, or second or third strokes on key combos)

I was looking for that long time ago. Can provide PR if you guide me and find interesting

**Comment by iandoug** [comment]
Um, KLE is a layout design tool... I think what you want is best done by having separate copies of the layout for each action you want to do. You seem to be basically describing "layers".

**Comment by albfan** [comment]
Yes, layers would be a great description. Any way to implement that based on KLE?

I would try something like a docker to run a server to expose a website like that

**Comment by albfan** [comment]
Nice, let me know if you want updates for these, I will close them.
