### ISSUE TITLE
"Raw data" allows a format that you can't paste into another service.

### ISSUE THREAD

**Issue by mhoye** [ijprest/keyboard-layout-editor#221]
I've discovered that the "raw data" part of k-l-e will recognize

[{x:5},{w:2},"key"]  

as being a single key, and display it as intended, but if I paste it into http://builder.swillkb.com/  it comes out broken,on that site, believing I meant two keys, the first of which is of width 1 and has no label.

[{x:5,w:2},"key"]   

works correctly and as intended, of course. I think this means {thing},{thing} should probably be considered an error and k-l-e should suggest (and generate!)  {thing,thing} instead.

Thank you for k-l-e, though, it's good fun and useful.

**Comment by iandoug** [comment]
the raw data view is json-lite ... use the Download -> Download JSON to get the proper json version for swill.

**Comment by iandoug** [comment]
Contrawise, if you're using the QMK firmware generator, you need to use the "lite" version ....

**Comment by ijprest** [comment]
FWIW, KLE *does* generate the second version.  (If you type the first version, then tweak it in any way using the editor, you'll see that the raw-data has change to the second version).  

The first version is still considered valid, though.  (I can't comment on what swillkb.com does/doesn't support.)
