### ISSUE TITLE
Key combos

### ISSUE THREAD

**Issue by eozaki** [ijprest/keyboard-layout-editor#229]
This is actually more like a question I didn't know where to post:
Is there a possibility to set a combo value to a given key?
E.g.: set `shift + '` to the top left corner key of the right half of the ergodone keyboard

**Comment by iandoug** [comment]
Um, KLE is mostly a design tool ... other things have to interpret how to handle what you put on the keys. There are 12 available slots on each key, you can put any character in any slot.

Not sure if that answers your question....

**Comment by eozaki** [comment]
It actually does.
Thank you for the help
