### ISSUE TITLE
Feature request: base64 symbol/image for keys.

### ISSUE THREAD

**Issue by c933103** [ijprest/keyboard-layout-editor#231]
Useful situations:
- User can put a custom icon onto the win key
- User can accurately reproduce shortcut keys (like +/- volume/brightness, and such) using graphics instead of relying on emoji
- Sometimes when user might prefer a particular glyph variant/font/look of a character, if custom image can be used then that can be included (Although specifying font might be a better answer in this case)

**Comment by ijprest** [comment]
Just put it in your key legend wrapped in an IMG tag, e.g.:
```
<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO     9TXL0Y4OHwAAAABJRU5ErkJggg=="/>
```
