### ISSUE TITLE
Keyboard layout download default filename

### ISSUE THREAD

**Issue by c933103** [ijprest/keyboard-layout-editor#236]
Now if you download a keyboard layout from the site as png/jpg/etc., the file name would always be "keyboard-layout.extension" by default. However, given that user can input the keyboard name in the website, would it be possible that when a keyboard name is given, the default downloaded file name would be changed the user-input keyboard-name instead of the pure "keyboard-layout.extension"?

**Comment by ijprest** [comment]
Pretty good suggestion...

**Comment by ijprest** [comment]
Should be working now for PNG, SVG, JSON, etc., downloads.  (You might have to Ctrl+F5 to refresh.)  Filenames are sanitized versions of the title, so expect spaces, slashes, etc., to be replaced.  We still fall back on "keyboard-layout.*" if there is no title. d557aedcd90e53241d6a946ab8498751ca44a23f
