### ISSUE TITLE
JSON with KeyCodes

### ISSUE THREAD

**Issue by dceonline** [ijprest/keyboard-layout-editor#247]
Is it possible to have a standalone keyboard using JSON for usage as keyboardtest, so one may build different keyboard-layouts to use with. And where can i put a kind of plugin for an extension to assign the code to the corresponding keys and add them to the JSON output?

**Comment by ijprest** [comment]
I don't know about 'keyboardtest', but KLE is currently all about the physical keyboard layout.  It does not currently handle scan-codes, etc.
