### ISSUE TITLE
Front Legend (.keyborder) height

### ISSUE THREAD

**Issue by ArmynC** [ijprest/keyboard-layout-editor#252]
How I can modify the Front Legend div height?

This variant do nothing:
`.keyborder {
    height: 100px;
}`
but if I edit this one in browser's console (inspect) it does work.

PS: 
1) How I can edit the [Top-Center-Bottom Legend] (div) box color (idependent from the rest of the key's colors & with different colors for more keys, not the same everywhere) ?
2) How can I edit the sides (Front Legend+left+right+up) of the buttons colors (to get them the same as the background)?
- I tried with an div but it changes all to the same color, I want to set them with their own colors...

**Comment by ArmynC** [comment]
What I want to achieve (example through inspect mode): 

![example_colors](https://user-images.githubusercontent.com/16375271/51250264-86497900-199e-11e9-8d69-58d931338fec.PNG)

I want the sides of the key to be the same as the background of the keyboard and to set different colours for more keys (in the center box).

**Comment by ijprest** [comment]
For (1), the editor does everything natively (using the 'properties' tab) except the "transparent" key sides, but you can do that with 'custom styles' (`.keyborder { background-color: transparent !important; }`). [Here's an example.](http://www.keyboard-layout-editor.com/##@_backcolor=%237d0000&css=.keyborder%20%7B%20background-color%2F:%20transparent%20!important%2F%3B%20%7D%3B&@_c=%2301753b&t=%23ffffff&a:7%3B&=TEST%0A%0A%0A%0ATEST&_c=%23cccccc&t=%23000000%0A%0A%0A%0A%23ffffff%3B&=TEST%0A%0A%0A%0ATEST&_c=%23ebf211%3B&=TEST%0A%0A%0A%0ATEST)

**Comment by ArmynC** [comment]
Thanks, at (1) works (first time I tried with a color, didin't knew about transparent) ...

But at (2) I tried `.keylabel10 { height: 100px !important; }` and it does not work, the `.keyborder { height: 100px !important; } ` worked but it did mess some keys from numpad (the center box is comes over front legend) 
![capture](https://user-images.githubusercontent.com/16375271/51271685-df320500-19d0-11e9-89dc-5b446c561075.PNG)

Also any advice for custom font -emoji display error-?

**Comment by ijprest** [comment]
For (2) (and PS2), ultimately we'd probably want to support some sort of custom profile (#209).  

For now, you can use CSS.  I think it would probably be better to *shrink* the "keytop" part of the key, rather than trying to make the sides bigger, so as to prevent alignment problems if you had a second row of keys.  You could do this with CSS:  

```css
.keytop { height: 38px !important; }
.keylabel9, .keylabel10, .keylabel11 { margin-top: -3px;}
```
Default height of 1u keys is 42px (for DCS/normal profiles), so the first rule shrinks this to 38px (-4px).  The second rule shifts the side labels (label9/10/11) up by 2px (default is -1px, so new value is -3px) to keep it centered.

(This won't work well if you have any keys that are > 1u tall...)

**Comment by ijprest** [comment]
To set a custom font in such a way as to not break character-picker emojis, see my response to #241.

**Comment by ArmynC** [comment]
Yeah, got everything done :+1: 

Using a font example:
`@import url(http://fonts.googleapis.com/css?family=Fredoka+One);
.keylabel0, .keylabel1, .keylabel2, 
.keylabel3, .keylabel4, .keylabel5, 
.keylabel6, .keylabel7, .keylabel8, 
.keylabel9, .keylabel10, .keylabel11 { 
   font-family: 'Fredoka One';
}`

Thanks :)
