### ISSUE TITLE
I'm a green hand. How to compile source code?

### ISSUE THREAD

**Issue by Var-iazioni** [ijprest/keyboard-layout-editor#262]
I want to compile source code and run on my computer.
I installed npm and required tools, try to run 'npm start' or other command, but it doesn't work.
My OS is windows10.
Do I have to install GNU make?
HELP!

**Comment by ijprest** [comment]
Yes.  Per the [README](https://github.com/ijprest/keyboard-layout-editor/blob/master/README.md), GNU make is required.

You can get pre-built Windows binaries from here: http://gnuwin32.sourceforge.net/packages/make.htm

It's just a single EXE; you can put it anywhere in your PATH.

**Comment by Var-iazioni** [comment]
> Yes. Per the [README](https://github.com/ijprest/keyboard-layout-editor/blob/master/README.md), GNU make is required.
> 
> You can get pre-built Windows binaries from here: http://gnuwin32.sourceforge.net/packages/make.htm
> 
> It's just a single EXE; you can put it anywhere in your PATH.

Thank you very much!
