### ISSUE TITLE
I've done my amazing design: and now?

### ISSUE THREAD

**Issue by pioz** [ijprest/keyboard-layout-editor#272]
I've just downloaded the JSON with my new keyboard design from the web app. Now I want it real. Where I can buy the keyset using the layout made with `keyboard-layout-editor`?

**Comment by guest20** [comment]
It might be easier to design a keyboard based on keycaps you have or to just rely on one of the generic sets of caps - 40% 60% TKL etc. Getting a bag full of custom injection moulded caps is a pretty costly.

As a good next step for hardware to have a look at http://builder.swillkb.com/  you can get it to generate the plans to cut a plate and case... then you just need some switches  / wire / diodes / controller and you're good to go.

A good next step for firmware is this guy: https://github.com/qmk/qmk_firmware

**Comment by ijprest** [comment]
To my knowledge, nobody will directly take the output from KLE and manufacture keycaps from them.

[Signature Plastics](https://pimpmykeyboard.com/) used to have an editor/designer on their site that was based on KLE (and customized for their capabilities), but I can't seem to find it now... it might be gone.  Regardless, I think it was intended for people setting up group buys with large minimum orders... and guest20 is right in that it would be prohibitively expensive for a one-off set.

Your best bet might be [WASD keyboards](https://www.wasdkeyboards.com/products/keycaps/keycap-set.html), who will print custom sets using a UV-printing technique.  It's not as durable as dye-sub or double-shot (like Signature Plastics does), and they have a limited range of keycap colors... but it's *much* cheaper.  Unfortunately, AFAIK they don't have any direct way to import data from KLE.
