### ISSUE TITLE
Migrate to https

### ISSUE THREAD

**Issue by agostaxyz** [ijprest/keyboard-layout-editor#280]
I know this is DNS stuff and not exactly on this project, but anyway browsers are slowly blocking http websites.

**Comment by hickford** [comment]
https://www.keyboard-layout-editor.com/

>  This site can’t be reached.  ERR_CONNECTION_TIMED_OUT

https would be great. @ijprest how do you host the site? Are there any issues that the community can help with?

https://letsencrypt.org/ can give you a certificate for free. Some servers even do it automatically https://caddyserver.com/

**Comment by ijprest** [comment]
Yeah... browsers are starting to get obnoxious about this.

Anyway... HTTPS now enabled.

For reference... it was hosted as an Amazon S3 static site... very easy, and the cost was only pennies per month.  Enabling SSL involved jumping through a *lot* of hoops... e.g., moving my DNS to AWS Route53, and setting up AWS CloudFront for global caching.  I don't think it'll significantly increase the cost (time will tell!)... but it sure increased the complexity!
