### ISSUE TITLE
Enhancement: matrix support

### ISSUE THREAD

**Issue by kbrock** [ijprest/keyboard-layout-editor#294]
What a great project! not sure if this request belongs here or in kle-serialize.

A number of tools use the kle format to generate things like plates, pcbs, and firmware. Many of these tools also need matrix information.

Is it possible to add the matrix to the kle specification?
By matrix, I mean the row and column used in the wiring layout.

You can probably auto increment the column for each key and auto increment the row for each new line. 
I was thinking having `mr, mc` or `matrix: [r, c]` would work depending upon how explicit and hierarchical you want to make it.

Thanks for listening

**Comment by adamws** [comment]
@kbrock
> You can probably auto increment the column for each key and auto increment the row for each new line.

won't work for some keys, space or ISO enter for example.

> Is it possible to add the matrix to the kle specification?

I like the approach of this project https://caniusevia.com/docs/layouts#switch-matrix-co-ordinates, perhaps dedicated fields would be nicer (instead of reusing legends) but I would not expect such feature anytime soon.

**Comment by kbrock** [comment]
> won't work for some keys, space or ISO enter for example.

Agreed. Iit probably won't work for tab, left shift, and many others.
But it works for a majority of the letters. at least for the whole q-p, a-;, z-/
Things like the tab and left shift even throw this for many. And keyboards like the gherkin have a seriously messed up matrix.


> but I would not expect such feature anytime soon.

agreed

Thanks for the reference/idea. I can totally work with that suggestion.
I'm actually trying to get location (x,y,r), matrix, and multiple layers (L1, L2)into a single layout. Probably a little too dense but it is getting close.
