### ISSUE TITLE
Copy key to existing position?

### ISSUE THREAD

**Issue by unityco** [ijprest/keyboard-layout-editor#305]
I feel like I'm probably missing something, but is there a way to "move" a key; ie take an existing key with labels and paste it on top of another?  When I do the copy/paste routine, the paste only creates a new key, even if my desired destination is selected.

Thanks!

**Comment by ijprest** [comment]
Easiest way to do what you want is probably:
1. Delete key at target location.
2. Copy/paste source key.  (The new key will be positioned at the "end" of the layout.)
3. Move the new key to the target location (you could edit the X & Y parameters directly, but it's easiest to just use the arrow keys on your keyboard).
