### ISSUE TITLE
Shift all keys feature

### ISSUE THREAD

**Issue by cduk** [ijprest/keyboard-layout-editor#309]
Sometimes, I want to start with a preset but add a row on the top or a column of keys on the left. Can we add a way to select all keys and then shift them all down or up?

**Comment by ijprest** [comment]
Select-all with Ctrl+A (or click+drag with your mouse to select a range).

Then move selected keycaps down with your arrow keys.

**Comment by cduk** [comment]
Thanks. I tried using the increase x, y buttons but that changed it for all selected keys.
