### ISSUE TITLE
Contacting the project owner?

### ISSUE THREAD

**Issue by chr11031** [ijprest/keyboard-layout-editor#316]
@ijprest and all the other contributors thank you for making this great keyboard project possible. Your work precedes you and is something I engage with regularly in my keyboard endeavors. Thank you for all your time and effort.

My question is - in the License.md file it is suggested that we can ask for a 'gratis' license permission simply by reaching out to @ijprest. I have not been able to find a way to reach out other than in an 'Issue' however. Is there a contact info section I am missing? Thanks.

I am asking in the context of a custom keyboard startup that would love to engage customers using some of the code in this project. Thank you! If licensing is not possible at this time, a simple rejection response will suffice. 

Again, much appreciation and thanks for all your contributions and creation!

**Comment by alerque** [comment]
c.f. #218 and #212

**Comment by ijprest** [comment]
@chr11031 Hrm... no DM's on GitHub.  DM me on Twitter (same username) with some details.  I don't use Twitter much, but I'll make a point to look for your message.

**Comment by chr11031** [comment]
@ijprest Unfortunately I get the following on Twitter:
![image](https://user-images.githubusercontent.com/12475888/185225743-e60a102e-1494-4fe4-85c4-6a0bff94efaa.png)

To change this setting (on your end) I found it under: 'Setting' -> 'Privacy and Safety' -> 'Direct Messages' -> 'Allow message requests from everyone'. 

Alternatively, I have followed you and believe you should be able to DM me on Twitter if you prefer to open a dialogue that way. my account has the same username as my GitHub (https://twitter.com/chr11031). 

Thank you for corresponding with me!

**Comment by chr11031** [comment]
@ijprest Can I have a follow-up to our correspondence? I have sent you a proposal.

Thanks

**Comment by DanielGGordon** [comment]
@ijprest I use KLE for my website ohkeycaps. I use it to manage some internals for keycap kits I offer. I send you a message on Twitter regarding the license.

**Comment by ijprest** [comment]
I replied to both of you.  Sorry for the delay.  My inbox gets pretty swamped at times, and it's easy to miss something once it's more than one page down.  :)

**Comment by chr11031** [comment]
Thank you!
