### ISSUE TITLE
Bulk Translate Keys

### ISSUE THREAD

**Issue by hughesjs** [ijprest/keyboard-layout-editor#318]
If I want to add keys to the left of a standard layout (say ISO 105 for instance), I'd expect to be able to highlight all the keys and then click the inc/dec buttons on the X/Y properties to make room for the new keys.

Instead, doing this seems to set the XY value of all the keys to whatever the (presumably first?) selected key is and they all end up in a heap.

![image](https://user-images.githubusercontent.com/4203766/191034001-a30f9c1c-0146-432c-9a01-3e42f7fa2082.png)

**Comment by ijprest** [comment]
Yeah, what you did has the effect of setting the 'x' value to the same thing for all the selected keys.  

To do what you want, select the keys you want to move, then use the arrow keys on your keyboard to move them.
