### ISSUE TITLE
how to add LED circles?

### ISSUE THREAD

**Issue by River-Mochi** [ijprest/keyboard-layout-editor#328]
Sorry for asking in here, there is no Discussions  activated for this github.

1.  Is there  a way I could add LED lights like this person did in this image?
This is for Viendi 8L  keyboard 

![image](https://user-images.githubusercontent.com/97197236/233189949-2853ce44-232b-4660-bae6-d650053bcd81.png)

My layout is [here ](http://www.keyboard-layout-editor.com/#/gists/919874feda1ab18bf9de8b74edc007b0)
I have no idea  how they added those LED lights and it's nice since they do exist. 

2.  is there a way to add  a Knob as a lot of keyboards have a knob now. the viendi 8L I'm working on has a knob in the numpad area.

**Comment by ijprest** [comment]
To achieve that effect, add a new key, give it a legend and color---`<i class='fa fa-circle'></i>`, from the Font Awesome character picker works well for the legend of an LED---then click the 'decal' checkbox at the bottom.

**Comment by River-Mochi** [comment]
> A 'knob' can be done the same way (with decals).

thanks @ijprest 

I got it now.  Can I use any Font awesome or only the ones that are here?  when I tried to use  a different Fontawesome from main website it did not work. but ones from your section worked.
![image](https://user-images.githubusercontent.com/97197236/233205455-827faa04-4a38-4a87-bfc4-0d013be22661.png)

**Comment by ijprest** [comment]
The glyphs in the character-picker are the only ones the editor provides; specifically, it uses an older version of FA.

However, you could probably load a *newer* version of FA (to get access to new FA glyphs) using some of the custom CSS stuff documented here: https://github.com/ijprest/keyboard-layout-editor/wiki/Custom-Styles

The [VIC-20 sample](http://www.keyboard-layout-editor.com/#/samples/commodore-vic20) shows the canonical way to add custom glyphs (see the 'custom styles' tab for the gory details).
