### ISSUE TITLE
Unable to log on to the website using github

### ISSUE THREAD

**Issue by SnappyRiffs** [ijprest/keyboard-layout-editor#330]
I tried to log on to the website using github but it gave 
![image](https://github.com/ijprest/keyboard-layout-editor/assets/97476091/0e1f6d2e-87af-4e02-b5ac-41072fa14f78)
How do I fix this?

**Comment by ijprest** [comment]
It's currently working for me.

It's possible it was a transient issue with the gatekeeper process (which runs on Azure).  So please try again.

If it still occurs, you could try some of the advice and/or workarounds on #250.
