### ISSUE TITLE
key layout

### ISSUE THREAD

**Issue by jsartain38826** [ijprest/keyboard-layout-editor#333]
is there a way to change direction of key layout?
i.e. on the enter key (number pad)
E
N
T
E
R

**Comment by ijprest** [comment]
There are multiple ways to do it, but the 'cleanest' might be with some custom styles.

1. Change your text from `ENTER` to `<span class='upright'>ENTER</span>`
2. Add this to the Custom Styles tab:  `.upright { writing-mode: vertical-rl; text-orientation: upright; }`


Here's an example demonstrating:  [(link)](http://www.keyboard-layout-editor.com/##@_css=.upright%20%7B%20writing-mode%2F:%20vertical-rl%2F%3B%20text-orientation%2F:%20upright%2F%3B%20%7D%3B&@_a:7&h:2%3B&=%3Cspan%20class%2F='upright'%3EENTER%3C%2F%2Fspan%3E)
