### ISSUE TITLE
Login Error while accessing GitHub

### ISSUE THREAD

**Issue by ahmetfkocaoglu** [ijprest/keyboard-layout-editor#340]
![error](https://github.com/ijprest/keyboard-layout-editor/assets/82767775/03b9bf00-dec6-4d26-98c6-eb01a8b0d376)

**Comment by guest20** [comment]
<img title="It's not just you! keyboard-layout-editor.com is down.
Last updated: Dec 31, 2023, 12:36 PM (1 second ago)" width="523" alt="Screen Shot 2023-12-31 at 12 36 18" src="https://github.com/ijprest/keyboard-layout-editor/assets/3603869/3cb6f3bd-1d2e-4dbf-a59c-a6c28ae66263">

**Comment by zaphodikus** [comment]
Works fine today

**Comment by wez** [comment]
broken again with the same gatekeeper error message today

**Comment by ijprest** [comment]
There has been some disruption as I enable HTTPS... I hope to have it resolved soon, but there are DNS and caching policies that are causing delays.

**Comment by guest20** [comment]
Oh! cool, https!

**Comment by ijprest** [comment]
Should be working again, post-HTTPS.
