### ISSUE TITLE
Cannot log in via github

### ISSUE THREAD

**Issue by kidpresident** [ijprest/keyboard-layout-editor#348]
Error code reads "Could not communicate with the gatekeeper process."

Cannot sign in, all saved layouts are inaccessible as there are no other log-in options.

**Comment by kidpresident** [comment]
Update: Now sign in portal for github says "the redirect_uri is not associated with this application."

**Comment by ijprest** [comment]
Was down for a while as I added HTTPS support.  Should be back up now.

**Comment by WandersFar** [comment]
It’s not working again.

**Comment by dmyoung9** [comment]
Well, I can't vouch for @WandersFar, because I have used KLE just fine since 2024, but this bug seems to have cropped up again.
