### ISSUE TITLE
Link to raw data as a separate file

### ISSUE THREAD

**Issue by doub** [ijprest/keyboard-layout-editor#56]
It would be nice to be able to click a link that would open the browser file download dialog to save the raw data as a simple file, rather than having to copy and paste it in another file editor.

Similarly it could be nice to somehow be able to upload a text file containing the raw data.

These two features would work best if the data was formatted as correct and complete JSON as proposed in issue #55.

**Comment by iandoug** [comment]
d1sc0tech has a fix for this.

**Comment by D1SC0tech** [comment]
My fork is a complete mess and I won't be able to fix it for a while, but I basically just used [file-saver.js](https://github.com/eligrey/FileSaver.js) to save a JSON file. As for loading, should be pretty easy.

**Comment by ijprest** [comment]
Done!  (1bb8b02efd1dde34d027b84ed82b57573947a73f and 3f44b1f866e98cc30ef04c7ab1eef7f5ec074ac4)

Thanks for the pointer to file-saver.js... worked well.
