### ISSUE TITLE
Try to save this

### ISSUE THREAD

**Issue by Vibex** [ijprest/keyboard-layout-editor#61]
{backcolor:"#232427"},
[{rx:2.75,ry:6.75,x:2,c:"#2d3238",t:"#525554",p:"DSA",a:7,f:8},"U"],
[{y:-6.5,x:-1.75},"W",{x:1},"P","V"],
[{y:-0.75,x:-2.75},"J"],
[{y:-0.5,x:-0.75},"S"],
[{y:-0.75,x:-1.75},"I",{x:1},"T","L"],
[{y:-0.75,x:-2.75},"A"],
[{y:-0.5,x:-0.75},"C"],
[{y:-0.75,x:-1.75},"X",{x:1},"G",{c:"#2b2c2e",t:"#857eb1",f:4,w:1.5},"Navigate"],
[{y:-0.75,x:-2.75,c:"#2d3238",t:"#525554",f:8},"Z"],
[{y:-0.25,x:0.75,c:"#2b2c2e",t:"#006d59",f:4,w:2,w2:1},"Space"],
[{x:1.75,t:"#2e6ea6"},"Alt"],
[{rx:10,ry:0,x:-1,c:"#2d3238",t:"#525554",f:8},"M"],
[{y:-0.75,x:-3},"B","Y",{x:1},"D"],
[{y:-0.75,x:1},"K"],
[{y:-0.5,x:-1},"E"],
[{y:-0.75,x:-3},"R","N",{x:1},"O"],
[{y:-0.75,x:1,f:4},"Pnc"],
[{y:-0.5,x:-1,f:8},"H"],
[{y:-0.75,x:-3.5,c:"#2b2c2e",t:"#d290b4",f:4,w:1.5},"Enter",{c:"#2d3238",t:"#525554",f:8},"F",{x:1},"Q"],
[{y:-0.75,x:1,f:4},"Shift"],
[{y:-0.25,x:-3.5,c:"#2b2c2e",t:"#ff6d1a",w:2},"Backspace"],
[{x:-3.5,t:"#b81b24"},"CTRL"]

**Comment by iandoug** [comment]
@ijprest: I have a fixed version of this.

**Comment by ijprest** [comment]
@iandoug:  I didn't see any serialization changes in your fork... did I miss something?  Regardless, I tracked down the serialization error and fixed it.

**Comment by iandoug** [comment]
Jordi was working on that code, so I didn't want to mess with it. Instead I fixed the layout data directly so that it loaded correctly. Did you get the email I sent you to the address in your commits?
