### ISSUE TITLE
XY-centered label + bottom right label

### ISSUE THREAD

**Issue by gioele** [ijprest/keyboard-layout-editor#63]
Mac keyboards have function buttons (for example the play/pause button) with a XY-centered label (the play/pause symbol) plus a smaller label on the bottom right (F8).

![apple-keyboard-shortcuts](https://cloud.githubusercontent.com/assets/237141/3254987/769c5490-f203-11e3-9857-01d0a68aa172.jpg)

With the current keyboard-layout-editor it is not possible to reproduce this layout.

**Comment by ijprest** [comment]
Implemented in 09a4e62607d9a08a7349eaa4b6c3eaf56086a9e5.  You can put up to 12 separate labels on each keycap, which should cover all alignment possibilities.
