### ISSUE TITLE
Allow entire selections to be moved/resized at once

### ISSUE THREAD

**Issue by Cribbit** [ijprest/keyboard-layout-editor#64]
All too often I'll get some area done, only to realize I want the whole thing .25 to the left. It would be great if we could move entire areas at once.

**Comment by D1SC0tech** [comment]
You can. Just select the keys you want to move and use the arrow keys to shift them around.

**Comment by ijprest** [comment]
Yeah... as @D1SC0tech mentioned, you can just multi-select your keys, then (with focus in the keyboard preview area) use the arrow keys to move them around.  

Keyboard only, at the moment, but I've got an enhancement request logged (#2) to eventually add mouse support.
