### ISSUE TITLE
Add switch type properties on individual keys

### ISSUE THREAD

**Issue by neechbear** [ijprest/keyboard-layout-editor#74]
It would be nice to specify a switch type for each key.

For example I would like to be able to indicate that I want a Cherry MX Green switch for CapsLock, ScrollLock and NumLock, Cherry MX Grey for Escape, Cherry MX White for all modifier keys, and Cherry MX Brown for everything else.

It would also be helpful to specify both with, and without LED for each switch.

**Comment by JordiOrlando** [comment]
Ooh, good idea. I really want to see if Swill can integrate his [Plate Builder] (http://builder.swillkb.com/) straight into kble. Sadly, it seems as though @ijprest has stopped working on the project, so I've forked the repo and will try to set it up on a server of my own.

Things I want to add (with help from others in the community):
* CSS for proper sculpted SA profile
* CSS for homing/deep-dish keycaps (DSA already done)
* More profiles like SP G20 or Cherry
* Support for custom fonts and graphical legends
* Keyboard layers. Add multiple function layers and flip between them with a selector
* Native support for Swill's Plate Builder
* Configurable switches (Cherry MX, Gateron, Alps, etc)
* Configurable LED colors

It's going to be a lot of work, and I'm in college, but I hope to work on it this summer.

**Comment by iandoug** [comment]
This has been done now.
