### ISSUE TITLE
Add counters for different key sizes

### ISSUE THREAD

**Issue by lennart96** [ijprest/keyboard-layout-editor#77]
This thing is really great, but there is one thing I'm missing: showing how many keys of different sizes are used in the design. This is very useful when trying to keep the design in line with an existing keyset.

Eg.

```
1 x 104
1.5 x 6
2 x 2
```

It think it's okay if just the most common keys are shown, with maybe other keys counted as 'others'.

**Comment by ijprest** [comment]
There's definitely a basic implementation of this in place, now, thanks to @iandoug.  We'll be enhancing it as we go along, so feel free to log more enhancement ideas if it doesn't fully meet your requirements.
