### ISSUE TITLE
YBX

### ISSUE THREAD

**Issue by iandoug** [ijprest/keyboard-layout-editor#79]
Hi 

YBX appears to be missing from the PBT colours.

thanks.

**Comment by ijprest** [comment]
I've added it (a5bfe89aae5a233ca40f7b706c3b8534979eb451).  Because I don't have a physical color chip to sample (it wasn't included with my color-sample ring), I just sampled their online photo, which won't be very accurate.  So I added a "not color corrected" disclaimer to the color name.

**Comment by iandoug** [comment]
Thanks, I'm sure it will be more than good enough for practical purposes :-)
