### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by alerque** [ijprest/keyboard-layout-editor#82]
Can you please clarify how this code is licensed? It seems by posting it on Github and advertising that you did so on the site that you're willing for it to be used, yet the LICENSE file says all rights reserved. What does that mean? Are we allowed to run this code ourselves? Host our own versions?

Would you be willing to change the license to some normal open source license such as one of the GPL variants (if you want to be sure to have access to contributions) or BSD/MIT etc (if you don't care)?

This would make it a lot more attractive for others to contribute back to the project.

**Comment by iandoug** [comment]
+1

**Comment by ijprest** [comment]
OK, I've added a LICENSE.md file (and linked from the website).  But I've left it as "all rights reserved" for now.

As I explain in the LICENSE file, the long-term plan is a permissive license (probably MIT).  However, I'd like to hold off on that until the site is more feature-complete, so we don't get a bunch of incompatible forks.  (There's still so much in the way of "low-hanging fruit" to be implemented that two implementations would diverge *very* quickly.)

But that's really my only goal with the current license; if you've got a use-case other than "host a general-purpose keyboard-layout editor for the enthusiast community", just get in touch and I'll grant a custom license (gratis!).

(I'll close this issue, but feel free to comment with additional concerns or suggestions.)

**Comment by D1SC0tech** [comment]
Great, I may do a PR if I have some brilliant idea, but for now I'm just content to use it. I'm also in the process of writing a similar website from scratch, so we'll see how that goes :p
