### ISSUE TITLE
multiple rotations borks permalink

### ISSUE THREAD

**Issue by alaricljs** [ijprest/keyboard-layout-editor#83]
Pasting this raw works, opening a new tab via the resulting permalink pukes.

[{r:17.1,rx:5.5,ry:5,h:1.5},""],
[{r:31,y:-1.25,x:1.35,h:1.5},""],
[{r:48.7,y:-1.75,x:2.625,h:1.5},""],
[{r:-48.7,rx:13,y:-1,x:-3.65,h:1.5},""],
[{r:-31,y:-0.25,x:-2.355,h:1.5},""],
[{r:-17.7,x:-1,y:-0.75,h:1.5},""]

**Comment by ijprest** [comment]
Confirmed; appears to a problem generating the link after touching the raw-data.  I'll get this fixed in the next update.

Workaround: before clicking on the link, tweak your design using the edit fields at least once (e.g., move a key and then move it back).
