### ISSUE TITLE
Standard num-row breaks save/load/permalink

### ISSUE THREAD

**Issue by alaricljs** [ijprest/keyboard-layout-editor#84]
Paste this in raw and try the permalink. (also if you do it the long way via gui)

["!\n1","@\n2","#\n3","$\n4","%\n5","_\n-","+\n=","^\n6","&\n7","*\n8","(\n9",")\n0"]

**Comment by ijprest** [comment]
Dup of #66, I believe.  The generated link doesn't work in Firefox 39, but works in IE & Chrome, as well as FF 41 (which has fixed the bug).

**Comment by alaricljs** [comment]
Yeah, Chrome doesn't mind it.  You must be right.
