### ISSUE TITLE
Show switch/key count

### ISSUE THREAD

**Issue by alaricljs** [ijprest/keyboard-layout-editor#88]
It would be convenient to display the total keys present in a layout for a couple reasons.  1: lazy people and complicated layouts ;)  2: a method to double check that there's not hidden keys that might end up causing multiple cut paths in CAD output.

**Comment by tylert** [comment]
Should this issue be closed now?  The current tool seems to have a summary tab showing switch/key counts.

**Comment by ijprest** [comment]
Yes.  Closing.
