### ISSUE TITLE
Problem with layout deserialization from URL

### ISSUE THREAD

**Issue by wlhlm** [ijprest/keyboard-layout-editor#90]
There's a problem with deserializing a layout from the URL in Firefox. My current workaround is to save a layout which replaces it with a hash in the URL.

[Random example URL grabbed from Reddit](http://www.keyboard-layout-editor.com/##@@_c=%23f00000%3B&=Esc&_c=%23808080%3B&=F1&=F2&=F3&=F4&_c=%23c0c0c0%3B&=F5&=F6&=F7&=F8&_c=%23808080%3B&=F9&=F10&=F11&=F12&_c=%23c0c0c0&w:1.75%3B&=%E2%96%BA%0A%0A%0A%0A%0A%0A%7C%7C&=I%E2%97%84%E2%97%84&=%E2%96%BA%E2%96%BAI&=%E2%96%A0&=Mute&=Scroll%0A%0A%0A%0A%0A%0ALock&=Pause%3B&@=~%0A%60&_x:-1%3B&=~%0A%60&=!%0A1&=%2F@%0A2&=%23%0A3&=$%0A4&=%25%0A5&=%0A6&=%2F&%0A7&=*%0A8&=(%0A9&=)%0A0&=%2F_%0A-&=+%0A%2F=&_w:1.75%3B&=Backspace&=Home&=Page%0A%0A%0A%0A%0A%0AUp&=NumLk&=%2F%2F&=*&=-%3B&@_w:1.5%3B&=Tab&=Q&=W&=E&=R&=T&=Y&=U&=I&=O&=P&=%7B%0A%5B&=%7D%0A%5D&_w:1.25%3B&=%7C%0A%5C&=End&=Page%0A%0A%0A%0A%0A%0ADown&=7&=8&=9&_h:2%3B&=+%3B&@_w:1.75%3B&=Caps%20Lock&=A&=S&=D&_n:true%3B&=F&=G&=H&_n:true%3B&=J&=K&=L&=%2F:%0A%2F%3B&=%22%0A%27&_w:2%3B&=Enter&=Delete&=Insert&=4&_n:true%3B&=5&=6%3B&@_w:2.25%3B&=Shift&=Z&=X&=C&=V&=B&=N&=M&=%3C%0A,&=%3E%0A.&=%3F%0A%2F%2F&_w:2.5%3B&=Shift&_c=%23808080%3B&=%E2%86%91&_c=%23c0c0c0%3B&=PrtScn&=1&=2&=3&_h:2%3B&=Enter%3B&@_w:1.25%3B&=Ctrl&_w:1.25%3B&=Win&_w:1.25%3B&=Alt&_w:6.25%3B&=&_w:1.25%3B&=Alt&_w:1.25%3B&=Win&_w:1.25%3B&=Ctrl&_c=%23808080%3B&=%E2%86%90&=%E2%86%93&=%E2%86%92&_c=%23c0c0c0&w:2%3B&=0&=.)

KLE throws `{{deserializeException}}`.

![Screenshot](https://cloud.githubusercontent.com/assets/1928113/8729540/17bcf276-2bec-11e5-98d7-dd05dd44889c.png)
__Platform__: Firefox 39.0 Win7 64bit

Everything works fine in Chrome.

**Comment by tuffff** [comment]
Got the same problem. It only seems to happen if there is a “%” somewhere in the json.

Happens with Firefox 39.0 and old Safari 5.1.7.

Cannot reproduce with current IE, Chrome and Opera.

**Comment by wlhlm** [comment]
I can no longer reproduce this with Firefox 44.0.1 on kble.com. Closing.
