### ISSUE TITLE
When visiting root url ... TypeError: keycap_html is not a function

### ISSUE THREAD

**Issue by jasonm23** [ijprest/keyboard-layout-editor#91]

**Comment by rudexi** [comment]
Same here. I get the same error code on firefox (windows and arch), and chrome (windows).
The issue make it impossible to perform any action.

**Comment by jasonm23** [comment]
I cloned and initiallised the jquery / dot vars affected just before they are called.

This is just so I can play with the editor.  (It works)

**Comment by ijprest** [comment]
Sorry about that.  Should be fixed now.

**Comment by jasonm23** [comment]
Thanks it worked
