### ISSUE TITLE
Make the question mark key actually work and not bring up the help dialogue

### ISSUE THREAD

**Issue by FenekAlfa** [ijprest/keyboard-layout-editor#96]
The title says it all. No matter whether I'm selecting text or moving the keycaps around, pressing "?" pops up the dialogue. I think F1 is much better for this purpose, because you don't press it to label a key "F1".

In case this is a bug, I'm on Linux Mint 17.2 and using newest stable build of Palemoon(25.4.1 (x64)).

**Comment by ijprest** [comment]
The help dialog is not supposed to be invoked if one of the edit controls has focus.  I wasn't experiencing any issues in the main branch, so it might be something specific to your browser.

However, I *was* seeing an issue in one of my development branches... so I made & deployed a change that fixed my branch, and that I hope will fix your scenario.

Please give it another try and let me know if it's still a problem.

**Comment by ijprest** [comment]
No followup, so I'm hoping this was fixed.  Feel free to re-open if it's still an issue.
